pipeline:
  identifier: Build_Krishna_hub_spec_harness_lambda_1732552554394
  name: Build harness_lambda
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1732552461282
        repoName: Krishna-hub-spec/harness_lambda
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: lint code
                  identifier: lint_code
                  spec:
                    shell: Bash
                    command: |-
                      #!/bin/bash

                      # Exit immediately if a command exits with a non-zero status
                      set -e

                      # Activate virtual environment
                      source .venv/bin/activate

                      # Run linter
                      flake8 main.py

                      echo "Linting completed successfully."
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -e .
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
